data:
  root:
  - /usr/xtmp/xs75/leaves/datasets/tiles/clean_tilesW512H512M4
  partition_file:
  - ../../stats/partition_qb_hole.json
  label_file: ../../stats/label_hole.json
  label_ratio: -1
  leaf_mask_ratio: -1
training:
  transform:
    toTensor: true
  hardware:
    workers: 2
    num_gpu: 1
model:
  name: Pretrained_Unet11
  load_from: /usr/xtmp/xs75/leaves/exps/qb_hole_img_white_20220222_105525/model_ep300_ckpt.pth.tar
  n_channels: 3
  n_classes: 1
  bilinear: false
evaluate:
  phase:
  - validation
  - testing
  save:
    log_root: /usr/xtmp/xs75/leaves/tmp/qb_hole_white_log
    is_activitions: true
    is_preds: false
    image:
      root: /usr/xtmp/xs75/leaves/datasets/acts
      type_name: qb_hole_white
    tile:
      root: null
      type_name: null
  single_target_img_id: null
  mask:
    name: leaf_mask
