name: leaf2
channels:
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - backcall=0.2.0
  - ca-certificates=2020.10.14
  - certifi=2020.6.20
  - decorator=4.4.2
  - ipython_genutils=0.2.0
  - jedi=0.17.2
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgomp=9.3.0
  - libstdcxx-ng=9.1.0
  - ncurses=6.2
  - openssl=1.1.1h
  - parso=0.7.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.2.4
  - ptyprocess=0.6.0
  - pygments=2.7.1
  - python=3.8.5
  - readline=8.1
  - setuptools=50.3.0
  - sqlite=3.35.4
  - tk=8.6.10
  - traitlets=5.0.5
  - tzdata=2020f
  - wcwidth=0.2.5
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - absl-py==0.15.0
    - argparse==1.4.0
    - asttokens==2.0.5
    - cachetools==4.2.4
    - charset-normalizer==2.0.7
    - colorama==0.4.4
    - cycler==0.11.0
    - easydict==1.9
    - executing==0.8.2
    - google-auth==2.3.3
    - google-auth-oauthlib==0.4.6
    - grpcio==1.41.1
    - i==2.1.0
    - idna==3.3
    - ipython==7.29.0
    - kiwisolver==1.3.2
    - markdown==3.3.4
    - matplotlib==3.4.3
    - matplotlib-inline==0.1.3
    - numpy==1.21.4
    - oauthlib==3.1.1
    - opencv-python==4.5.4.58
    - path==16.2.0
    - pillow==8.4.0
    - prompt-toolkit==2.0.10
    - protobuf==3.19.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==3.0.5
    - python-dateutil==2.8.2
    - pyyaml==6.0
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - six==1.16.0
    - tensorboard==2.7.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - torch==1.10.0
    - torchvision==0.11.1
    - tqdm==4.62.3
    - typing-extensions==3.10.0.2
    - urllib3==1.26.7
    - werkzeug==2.0.2

