images:
  root: '/usr/xtmp/xs75/leaves/datasets_updated/leaves'
  dirs: [quercus-bicolor-herbivory] #quercus-bicolor-herbivory, onoclea-sensibilis-herbivory, quercus-lobata
  subdirs:
    image: 'images_clean/*.j*g'
    label: 'releases/3.0-qb-corrected-test-val/other_formats/semantic_mask/masks_clean/*.png'
    leaf_mask: 'images_clean_leaf_mask/*.png'
  subdir_labelmap: 'releases/3.0-qb-corrected-test-val/other_formats/semantic_mask/class_mapping.csv'

label:
  label_file: '../../stats/label_skel.json' #label_skel.json' label_margin.json label_file_common_binary.json
  overwrite: False
  binary: True

tiles:
  root: '/usr/xtmp/xs75/leaves/datasets_updated/tiles/tiles_skel_3.0'
  dirs: [quercus-bicolor-herbivory] #quercus-bicolor-herbivory, onoclea-sensibilis-herbivory, quercus-lobata
  subdirs:
    image: 'image/*/*.jpeg'
    label: 'label/*/*.png'
    leaf_mask: 'leaf_mask/*/*.png'

  width: 512
  height: 512
  margin: 4
  overwrite: False

partition:
  training: 0.6
  validation: 0.1
  partition_file: '../../stats/updated/original_partition_qb_skel_3.0.json'
  overwrite: True
  old_parition_order:  '../../stats/updated/partition.json' #should deleted soon

